Repository Dev-FE-2/toy-project2-team1, pull requests merged in 2024-12, with the labels that each got.

#56 [✨ Feature] 테이블-페이지네이션 기능구현
  package-lock.json
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/index.ts
  src/components/pagination/pagination.style.ts
  src/components/pagination/pagination.tsx
  src/components/salaryselect/salaryButton.styled.ts
  src/components/salaryselect/salaryButton.tsx
  src/components/salaryselect/salarySelect.style.ts
  src/components/salaryselect/salarySelect.tsx
  src/components/table/table.styled.ts
  src/components/table/table.tsx
  src/pages/index.ts
  src/pages/salary-details/SalaryDetails.tsx
  src/pages/salary-user/SalaryDetails.styles.ts
  src/pages/salary-user/SalaryDetails.tsx
Labels: ✨ Feature

#60 [✨ Feature] 일정 추가, 삭제 폼 유효성 검사, 스타일링 수정
  package-lock.json
  package.json
  src/components/Login/Login.styles.ts
  src/components/Login/LoginForm.tsx
  src/components/button/Button.styles.ts
  src/components/checkbox/CheckboxItem.tsx
  src/components/input/Input.style.ts
  src/components/input/input.tsx
  src/components/modal/ScheduleModal.tsx
  src/components/register/RegisterForm.tsx
  src/components/schedule-management/clalendar/Calendar.styles.ts
  src/components/schedule-management/clalendar/Calendar.tsx
  src/components/schedule-management/schedule-card/UserScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.styles.ts
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.styles.ts
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/components/schedule-management/test.json
  src/components/toggle/Toggle.styles.ts
  src/components/toggle/Toggle.tsx
  src/hooks/useDebounce.ts
  src/pages/Home/Home.tsx
  src/pages/schedule-management/ScheduleManagement.styles.ts
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/actions/userAction.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/reducers/userReducer.ts
  src/redux/store.ts
  src/styles/GlobalStyles.ts
  src/styles/designTokens.css
  src/types/auth.ts
  src/types/schedule.ts
  src/utils/calculateScheduleShiftType.ts
  src/utils/calculateScheduleTimeCategory.ts
  src/utils/filteredRepeatSchedules.ts
  src/utils/generateRepeatingSchedules.ts
Labels: ✨ Feature, 🎨 Style

#69 [✨ Feature] 년,월 기준으로 데이터 필터 ✨ Feature
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/salaryselect/salarySelect.tsx
  src/components/table/table.tsx
  src/pages/salary-user/SalaryDetails.tsx
Labels: ✨ Feature

#70 [✨ Feature] 관리자 전체 직원 일정 관리 보여주기
  src/components/index.ts
  src/components/schedule-management/clalendar/admin-calendar/AdminCalendar.tsx
  src/components/schedule-management/clalendar/user-calendar/Calendar.tsx
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
Labels: ✨ Feature

#72 [✨ Feature] 관리자 해당 날짜에 맞는 전체 직원 일정 확인하기
  src/components/schedule-management/clalendar/admin-calendar/AdminCalendar.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/ScheduleList.tsx
  src/components/schedule-management/schedule-list/admin-schedule-list/adminScheduleList.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/pages/schedule-management/ScheduleManagement.tsx
Labels: ✨ Feature

#68 [🔄 Refactor] redux-persist로 새로고침시에도 데이터 유지
  package-lock.json
  package.json
  src/components/index.ts
  src/components/schedule-management/calendar/Calendar.styles.ts
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/calendar/admin-calender/AdminCalender.tsx
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/clalendar/user-calendar/Calendar.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/ScheduleList.tsx
  src/components/schedule-management/schedule-list/admin-schedule-list/adminScheduleList.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useIsAdmin.ts
  src/main.tsx
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/store.ts
  src/types/schedule.ts
  src/utils/calculateEndDateTime.ts
  src/utils/calculateScheduleShiftType.ts
  src/utils/dateFormatter.ts
  src/utils/filterSchedulesByDate.ts
  src/utils/generateRepeatingSchedules.ts
Labels: 🔄 Refactor

#77 [✨ Feature] 모달 전역 상태 관리 추가 / 스케줄 수정, 삭제 폼 모달 연결
  src/components/modal/Modal.styles.ts
  src/components/modal/Modal.tsx
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.styles.ts
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useScheduleManage.ts
  src/redux/actionTypes.ts
  src/redux/actions/modalActions.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/modalReducer.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/reducers/userReducer.ts
  src/redux/store.ts
  src/types/modal.ts
  src/types/schedule.ts
  src/utils/calculateEndDateTime.ts
  src/utils/calculateScheduleShiftType.ts
Labels: ✨ Feature

#78 [🔄 Refactor] 관리자 일정 관리 목록 불러오기 (firebase->sueprbase) 리팩토링 (#75)
  src/components/schedule-management/calendar/admin-calender/AdminCalender.tsx
  src/redux/actions/scheduleActions.ts
Labels: 🔄 Refactor

#79 [✨ Feature] 급여 명세 버튼, 정정신청 버튼 모달 구현
  .eslintrc.cjs
  src/components/PaginatedTable/DetailModal/detailModal.style.ts
  src/components/PaginatedTable/DetailModal/detailModal.tsx
  src/components/PaginatedTable/EditModal/editModal.style.ts
  src/components/PaginatedTable/EditModal/editModal.tsx
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/modal/Modal.styles.ts
  src/components/salaryselect/salaryButton.styled.ts
  src/components/salaryselect/salaryButton.tsx
  src/components/salaryselect/salarySelect.tsx
  src/components/table/table.tsx
  src/pages/salary-user/SalaryDetails.tsx
Labels: ✨ Feature

#83 schedule_id 중복 대응해 scheduleActions 수정
  src/components/schedule-management/calendar/admin-calender/AdminCalender.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/pages/index.ts
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/store.ts
Labels: 🔄 Refactor

#84 [✨ Feature] 정정신청 파일 추가 기능
  src/components/PaginatedTable/EditModal/editModal.tsx
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/table/table.tsx
Labels: ✨ Feature

#90 [🔧 Fix] schedule modal form 수정, crud 테스트
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useScheduleManage.ts
  src/types/schedule.ts
  src/utils/dateFormatter.ts
Labels: 🔧 BugFix

#89 [🔄 Refactor] 폴더명 및 컴포넌트 파일명 대소문자 규칙에 맞게 변경
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/salaryselect/SalarySelect.style.ts
  src/components/salaryselect/SalarySelect.tsx
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.styles.ts
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.tsx
  src/components/table/Table.styled.ts
  src/components/table/Table.tsx
  src/pages/home/Home.styles.ts
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/register/Register.styles.ts
  src/pages/register/Register.tsx
Labels: 🔄 Refactor

#93 [🔄 Refactor] 일정 추가, 수정 폼 유효성 검사 수정
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/types/schedule.ts
Labels: 🔄 Refactor

#99 [🐛 Bug] 컴포넌트 이름 변경 미 인식으로 인한 문제해결
  src/components/Login/Login.styles.ts
  src/components/Login/LoginForm.tsx
  src/components/Login/LoginValidation.tsx
  src/pages/Profile/Profile.styles.ts
  src/pages/Profile/Profile.tsx
Labels: 🔧 BugFix

#103 [🔧 Fix] 로그인 페이지 로그인폼 삭제로 인한 재설정
  src/pages/login/Login.tsx
Labels: 🔧 BugFix

#106 [✨ Feature] 관리자 직원 일정 관리 수정, 삭제 구현
  src/components/index.ts
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-list/ScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useScheduleManage.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/employeeActions.ts
  src/redux/reducers/employeeReducer.ts
  src/redux/store.ts
  src/types/schedule.ts
Labels: ✨ Feature

#112 [✨ Feature] 프로필 페이지 디자인 및 기능구현
  src/components/login/Login.styles.ts
  src/components/login/LoginForm.tsx
  src/components/login/LoginValidation.tsx
  src/components/nav/Navbar.tsx
  src/components/register/FormValidation.tsx
  src/components/register/RegisterForm.tsx
  src/hooks/useIsAdmin.ts
  src/hooks/useLoginAuthObserver.ts
  src/hooks/useRegister.ts
  src/pages/profile/Profile.styles.ts
  src/pages/profile/Profile.tsx
  src/routes/router.tsx
  src/types/auth.ts
  src/types/register.ts
Labels: ✨ Feature, 🔄 Refactor

#111 [✨ Feature] 정정신청 버튼 기준 및 모달 추가
  package-lock.json
  package.json
  src/components/PaginatedTable/EditModal/editModal.tsx
  src/components/PaginatedTable/EditModal/hook/useSupabaseData.ts
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/table/Table.tsx
  src/types/salary.ts
Labels: ✨ Feature, 🔄 Refactor

#110 [🔄 Refactor] 코드 구조 개선
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/index.ts
  src/components/login/LoginForm.tsx
  src/components/modal/ModalPortal.tsx
  src/components/nav/Navbar.tsx
  src/components/schedule-management/calendar/Calendar.styles.ts
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/calendar/admin-calender/AdminCalender.tsx
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.styles.ts
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.styles.ts
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/components/search/SearchEmplyeeList.tsx
  src/constants/fiteredCalendar.ts
  src/hooks/useDebounce.ts
  src/pages/salary-management/SalaryManagement.tsx
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/employeeActions.ts
  src/redux/actions/scheduleActions.ts
  src/redux/actions/userActions.ts
  src/redux/reducers/adminUserIdReducer.ts
  src/redux/reducers/employeeReducer.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/store.ts
  src/types/schedule.ts
Labels: 🔄 Refactor

#113 [✨ Feature] 사용자,관리자 필터에 따른 일정관리 목록 보여주기 구현
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/checkbox/CheckboxGroup.tsx
  src/components/checkbox/CheckboxItem.tsx
  src/components/home/MainLayout.styles.ts
  src/components/home/MainLayout.tsx
  src/components/login/LoginForm.tsx
  src/components/nav/Navbar.tsx
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/constants/fiteredCalendar.ts
  src/hooks/useLoginAuthObserver.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actions/scheduleActions.ts
  src/redux/actions/userActions.ts
Labels: ✨ Feature

#115 [✨ Feature] 캘린더 컴포넌트 홈 화면에 적용
  src/components/checkbox/CheckboxGroup.tsx
  src/components/checkbox/CheckboxItem.tsx
  src/components/home/MainLayout.styles.ts
  src/components/home/MainLayout.tsx
  src/components/index.ts
  src/components/login/LoginForm.tsx
  src/components/schedule-management/calendar/Calendar.styles.ts
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/calendar/user-calender/UserCalendar.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/pages/schedule-management/ScheduleManagement.styles.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
  src/redux/store.ts
  src/types/schedule.ts
Labels: ✨ Feature

#124 [✨ Feature] calendar 전역 변경
  src/components/checkbox/CheckboxItem.tsx
  src/components/home/MainLayout.tsx
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useFiltereSchedulesByCategory.ts
  src/redux/actionTypes.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
  src/types/schedule.ts
  src/utils/filterSchedules.ts
Labels: ✨ Feature

#122 [🔄 Refactor] 관리자 일정 목록에서 카테고리 -> 직원 이름 변경
  src/components/schedule-management/calendar/Calender.tsx
Labels: 🔄 Refactor

#129 [🔄 Refactor] admin form, 회원가입 페이지 디자인 수정
  src/components/button/Button.styles.ts
  src/components/index.ts
  src/components/login/Login.styles.ts
  src/components/login/LoginForm.tsx
  src/components/register/Register.styles.ts
  src/components/register/RegisterForm.tsx
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/checkbox/CheckboxGroup.tsx
  src/components/schedule-management/checkbox/CheckboxItem.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/ScheduleList.styles.ts
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.styles.ts
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.styles.ts
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/components/schedule-management/search/SearchEmployeeList.styles.ts
  src/components/schedule-management/search/SearchEmployeeList.tsx
  src/components/search/SearchEmplyeeList.style.ts
  src/components/search/SearchEmplyeeList.tsx
  src/pages/correction-request/CorrectionRequest.styles.ts
  src/pages/correction-request/CorrectionRequest.tsx
  src/pages/index.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actions/employeeActions.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/adminUserIdReducer.ts
  src/redux/reducers/employeeReducer.ts
  src/redux/store.ts
  src/routes/router.tsx
  src/utils/dateFormatter.ts
Labels: ✨ Feature, 🎨 Style

#128 [✨ Feature] 메인화면 급여명세서 및 에러화면표기
  src/components/PaginatedTable/DetailModal/MainDetailModal.tsx
  src/components/PaginatedTable/EditModal/hook/useSupabaseData.ts
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/home/MainLayout.tsx
  src/components/schedule-management/calendar/Calender.tsx
Labels: ✨ Feature

#131 [🔄 Refactor] navbar 디자인토큰 사용
  src/components/PaginatedTable/DetailModal/MainDetailModal.tsx
  src/components/home/MainLayout.tsx
  src/components/nav/Navbar.styles.ts
  src/components/nav/Navbar.tsx
  src/components/nav/NavbarItem.tsx
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.styles.ts
Labels: 🔄 Refactor

#134 [🔄 Refactor]세금공제 데이터 누락 수정
  src/components/PaginatedTable/DetailModal/MainDetailModal.tsx
  src/components/PaginatedTable/DetailModal/detailModal.style.ts
  src/components/PaginatedTable/DetailModal/detailModal.tsx
  src/components/PaginatedTable/EditModal/hook/useSupabaseData.ts
  src/components/home/MainLayout.tsx
Labels: 🔄 Refactor

#138 [✨ Feature] 정정신청확인 추가
  src/components/PaginatedTable/CheckingResult/checkingResult.styled.ts
  src/components/PaginatedTable/CheckingResult/checkingResult.tsx
  src/components/PaginatedTable/DetailModal/detailModal.style.ts
  src/components/PaginatedTable/DetailModal/detailModal.tsx
  src/components/PaginatedTable/PaginatedTable.tsx
  src/pages/application details/ApplicationDeatils.styled.ts
  src/pages/application details/ApplicationDetails.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#136 [✨ Feature] 관리자 스케줄 리스트 근무시간추가, css 추가
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.styles.ts
  src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.styles.ts
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actions/scheduleActions.ts
  src/types/schedule.ts
Labels: ✨ Feature, 🎨 Style

#140 [✨ Feature] title 및 아이콘 수정
  index.html
  public/showtime.ico
  public/vite.svg
  src/utils/generateRepeatingSchedules.ts
Labels: ✨ Feature

#142 [🔄 Refactor] 급여내역 카테고리 조정
  src/components/PaginatedTable/DetailModal/detailModal.tsx
  src/components/PaginatedTable/EditModal/editModal.tsx
  src/components/PaginatedTable/PaginatedTable.tsx
  src/hooks/useSalaryUserData.ts
  src/pages/application details/ApplicationDetails.tsx
  src/pages/salary-management/SalaryManagement.tsx
Labels: 🔄 Refactor

#148 [📚 Docs] README.md 작성하기
  README.md
Labels: 📃 Docs

#145 [🔧 Fix] 근무 시간 영역 주차 계산 수정 및 쿼리 수정
  src/components/home/MainLayout.styles.ts
  src/components/home/MainLayout.tsx
  src/hooks/useWorkingHours.ts
Labels: 🔧 BugFix

#149 [🔧 Fix] 발표 준비하며 이상한 부분 수정
  src/components/home/MainLayout.styles.ts
  src/components/home/WorkingHours.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/utils/filteredRepeatSchedules.ts
  src/utils/generateRepeatingSchedules.ts
Labels: 🔧 BugFix

#151 [📚 Docs] README.md 수정
  README.md
  vercel.json
Labels: 📃 Docs

#160 [🔧 Fix] 스케줄 반복 일정 계산 로직 개선, 수정 로직 개선
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useScheduleManage.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actions/scheduleActions.ts
  src/utils/dateFormatter.ts
  src/utils/filterSchedules.ts
  src/utils/filteredRepeatSchedules.ts
Labels: 🔧 BugFix

#163 [🔄 Refactor] ErrorBoundary, Suspense 적용
  package-lock.json
  package.json
  src/App.tsx
  src/components/button/Button.styles.ts
  src/components/error/Error.styles.ts
  src/components/error/Error.tsx
  src/components/home/MainLayout.tsx
  src/components/home/WorkingHours.tsx
  src/components/index.ts
  src/components/loader/Loader.styles.ts
  src/components/loader/Loader.tsx
  src/components/loading/Loading.tsx
  src/components/login/LoginForm.tsx
  src/components/schedule-management/calendar/Calendar.styles.ts
  src/components/schedule-management/calendar/Calender.tsx
  src/components/schedule-management/schedule-add-button/ScheduleAddButton.tsx
  src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.styles.ts
  src/components/schedule-management/schedule-card/user-schedule-card/UserScheduleCard.tsx
  src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx
  src/components/schedule-management/schedule-modal/ScheduleModal.tsx
  src/hooks/useScheduleManage.ts
  src/pages/schedule-management/ScheduleManagement.tsx
  src/redux/actionTypes.ts
  src/redux/actions/employeeActions.ts
  src/redux/actions/scheduleActions.ts
  src/redux/reducers/scheduleReducer.ts
  src/types/schedule.ts
  src/utils/filteredRepeatSchedules.ts
  vite.config.ts
Labels: 🔄 Refactor

#165 [🔄 Refactor] 사용자 급여 내역 페이지 select 최신 월로 설정, 급여에 `,` 구분자 추가
  src/components/PaginatedTable/DetailModal/detailModal.style.ts
  src/components/PaginatedTable/DetailModal/detailModal.tsx
  src/components/PaginatedTable/EditModal/editModal.tsx
  src/components/PaginatedTable/PaginatedTable.tsx
  src/components/footer/Footer.style.ts
  src/components/table/Table.tsx
  src/hooks/useSalaryUserData.ts
  src/utils/salaryFormatter.ts
Labels: 🔄 Refactor

#170 [✨ Feature] 회원관련 기능 슈퍼베이스 users 테이블로 변경
  src/components/schedule-management/calendar/Calender.tsx
  src/hooks/useRegister.ts
  src/pages/profile/Profile.tsx
Labels: ✨ Feature, 🔄 Refactor
